project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/raphaelbalzer
format:
  html:
    toc: true
    theme: minty
    css: styles.css

editor: visual